### ISSUE TITLE
Feature: Add support for oneof fields

### ISSUE THREAD

**Issue by abronan** [favadi/protoc-go-inject-tag#19]
There seems to be no ability to inject tags on `oneof` fields. This could be useful to be able to inject both at the root of the `oneof` and at the level of individual fields inside that `oneof` such as:

```go
message Object {
        [...]
        // @inject_tag tag:"moomeh"
        oneof moomeh {
	        // @inject_tag tag:"moo"
	        string moo = 16;
	        // @inject_tag tag:"meh"
	        int64 meh = 17;
        }
}
```

Would thus generate:

```go
        [...]
	// Types that are valid to be assigned to Moomeh:
	//	*Object_Moo
	//	*Object_Meh
	Moomeh isObject_Moomeh `protobuf_oneof:"moomeh" tag:"moomeh"`
}

[...]

type Object_Moo struct {
	Moo string `protobuf:"bytes,16,opt,name=moo,proto3,oneof" tag:"moo"`
}
type Object_Meh struct {
	Meh int64 `protobuf:"varint,17,opt,name=meh,proto3,oneof" tag:"meh"`
}
```

**Comment by lrstanley** [comment]
This looks to be working today with the latest version of protoc-go-inject-tag (main struct field, as well as children struct fields), though your example looks to be missing the required colon. What your example is using:

```
@inject_tag tag:"moomeh"
```

What it should be:
```
@inject_tag: tag:"moomeh"
```

If others are still experiencing issues today, may need to provide additional info, otherwise I think this can be closed.

**Comment by abronan** [comment]
Thank you @lrstanley, it has been a long time since I have opened this issue and surely things have been fixed in the meantime, I will close it.
