### ISSUE TITLE
Fails with index out of range on streams

### ISSUE THREAD

**Issue by veqryn** [favadi/protoc-go-inject-tag#26]
`protoc-go-inject-tag` fails when I have a stream:
```bash
$ protoc-go-inject-tag.exe -input=./stuff.pb.go                                                                                                                             2018/09/19 19:18:32 parsing file "./stuff.pb.go" for inject tag comments
panic: runtime error: index out of range

goroutine 1 [running]:
main.parseFile(0xc0420960c7, 0x35, 0x0, 0x0, 0x0, 0x535d10, 0x21, 0xc042062210, 0xc04208bf20, 0x4e6dbb)
        C:/Users/xxx/go/src/github.com/favadi/protoc-go-inject-tag/file.go:74 +0xc77
main.main()
        C:/Users/xxx/go/src/github.com/favadi/protoc-go-inject-tag/main.go:26 +0x152
```

I've managed to reduce my proto file to the following while still getting the error:
```proto
syntax = "proto3";

package stuff;
option go_package = "proto";

service Stuff {
	rpc GetStuff (Params) returns (stream Record) {}
}


message Params {
	// @inject_tag: validate:"omitempty"
	string id = 1;
}

message Record {
	string id = 1;
}
```

I have reduce my protoc command to this, I still have the problem with protoc-go-inject-tag: `protoc -I=. ./stuff.proto --go_out=plugins=grpc:.`

**Comment by lrstanley** [comment]
Testing this on the latest version of protoc-go-inject-tag, and I can't seem to replicate (latest protoc-gen-go and protoc-gen-go-grpc plugins). It seems to generate both the `.pb.go` and `<name>_grpc.pb.go` successfully, and add/merge the necessary tags.

Assume this can be closed, as it's likely been fixed with prior commits and/or very old versions of grpc/protoc-go plugins. If that's not the case, may need additional info.
